set_property SRC_FILE_INFO {cfile:C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/constrs_1/imports/Desktop/Nexys-4-DDR-Master.xdc rfile:../../../CISC24.srcs/constrs_1/imports/Desktop/Nexys-4-DDR-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN E3 IOSTANDARD LVCMOS33} [get_ports CLK]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports {Sel[0]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L16 IOSTANDARD LVCMOS33} [get_ports {Sel[1]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS33} [get_ports {DebugSel}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R15 IOSTANDARD LVCMOS33} [get_ports DinSw[0]]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {DinSw[1]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T18 IOSTANDARD LVCMOS33} [get_ports {DinSw[2]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U18 IOSTANDARD LVCMOS33} [get_ports {DinSw[3]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R13 IOSTANDARD LVCMOS33} [get_ports {DinSw[4]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T8 IOSTANDARD LVCMOS18} [get_ports {DinSw[5]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS18} [get_ports {DinSw[6]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {DinSw[7]}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T13 IOSTANDARD LVCMOS33} [get_ports {DinSw[8]}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H6 IOSTANDARD LVCMOS33} [get_ports {RegSel[0]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {RegSel[1]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U11 IOSTANDARD LVCMOS33} [get_ports {RegSel[2]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports Rst]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {inttest[0]}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K15 IOSTANDARD LVCMOS33} [get_ports {inttest[1]}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J13 IOSTANDARD LVCMOS33} [get_ports {inttest[2]}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N14 IOSTANDARD LVCMOS33} [get_ports {inttest[3]}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {CCR[0]}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {CCR[1]}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {CCR[2]}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U16 IOSTANDARD LVCMOS33} [get_ports {CCR[3]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T10 IOSTANDARD LVCMOS33} [get_ports {Cathode[7]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN R10 IOSTANDARD LVCMOS33} [get_ports {Cathode[6]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports {Cathode[5]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS33} [get_ports {Cathode[4]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {Cathode[3]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T11 IOSTANDARD LVCMOS33} [get_ports {Cathode[2]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN L18 IOSTANDARD LVCMOS33} [get_ports {Cathode[1]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports {Cathode[0]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J17 IOSTANDARD LVCMOS33} [get_ports {Anode[0]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J18 IOSTANDARD LVCMOS33} [get_ports {Anode[1]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T9 IOSTANDARD LVCMOS33} [get_ports {Anode[2]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN J14 IOSTANDARD LVCMOS33} [get_ports {Anode[3]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN P14 IOSTANDARD LVCMOS33} [get_ports {Anode[4]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {Anode[5]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN K2 IOSTANDARD LVCMOS33} [get_ports {Anode[6]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN U13 IOSTANDARD LVCMOS33} [get_ports {Anode[7]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN F4 IOSTANDARD LVCMOS33} [get_ports PS2_CLK]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN B2 IOSTANDARD LVCMOS33} [get_ports PS2_DATA]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list CLK_IBUF]]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {CISC24HW_i/ALUMuxB_0_Dout[0]} {CISC24HW_i/ALUMuxB_0_Dout[1]} {CISC24HW_i/ALUMuxB_0_Dout[2]} {CISC24HW_i/ALUMuxB_0_Dout[3]} {CISC24HW_i/ALUMuxB_0_Dout[4]} {CISC24HW_i/ALUMuxB_0_Dout[5]} {CISC24HW_i/ALUMuxB_0_Dout[6]} {CISC24HW_i/ALUMuxB_0_Dout[7]} {CISC24HW_i/ALUMuxB_0_Dout[8]} {CISC24HW_i/ALUMuxB_0_Dout[9]} {CISC24HW_i/ALUMuxB_0_Dout[10]} {CISC24HW_i/ALUMuxB_0_Dout[11]} {CISC24HW_i/ALUMuxB_0_Dout[12]} {CISC24HW_i/ALUMuxB_0_Dout[13]} {CISC24HW_i/ALUMuxB_0_Dout[14]} {CISC24HW_i/ALUMuxB_0_Dout[15]} {CISC24HW_i/ALUMuxB_0_Dout[16]} {CISC24HW_i/ALUMuxB_0_Dout[17]} {CISC24HW_i/ALUMuxB_0_Dout[18]} {CISC24HW_i/ALUMuxB_0_Dout[19]} {CISC24HW_i/ALUMuxB_0_Dout[20]} {CISC24HW_i/ALUMuxB_0_Dout[21]} {CISC24HW_i/ALUMuxB_0_Dout[22]} {CISC24HW_i/ALUMuxB_0_Dout[23]}]]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {CISC24HW_i/AccumReg_0_Accum_Out[0]} {CISC24HW_i/AccumReg_0_Accum_Out[1]} {CISC24HW_i/AccumReg_0_Accum_Out[2]} {CISC24HW_i/AccumReg_0_Accum_Out[3]} {CISC24HW_i/AccumReg_0_Accum_Out[4]} {CISC24HW_i/AccumReg_0_Accum_Out[5]} {CISC24HW_i/AccumReg_0_Accum_Out[6]} {CISC24HW_i/AccumReg_0_Accum_Out[7]} {CISC24HW_i/AccumReg_0_Accum_Out[8]} {CISC24HW_i/AccumReg_0_Accum_Out[9]} {CISC24HW_i/AccumReg_0_Accum_Out[10]} {CISC24HW_i/AccumReg_0_Accum_Out[11]} {CISC24HW_i/AccumReg_0_Accum_Out[12]} {CISC24HW_i/AccumReg_0_Accum_Out[13]} {CISC24HW_i/AccumReg_0_Accum_Out[14]} {CISC24HW_i/AccumReg_0_Accum_Out[15]} {CISC24HW_i/AccumReg_0_Accum_Out[16]} {CISC24HW_i/AccumReg_0_Accum_Out[17]} {CISC24HW_i/AccumReg_0_Accum_Out[18]} {CISC24HW_i/AccumReg_0_Accum_Out[19]} {CISC24HW_i/AccumReg_0_Accum_Out[20]} {CISC24HW_i/AccumReg_0_Accum_Out[21]} {CISC24HW_i/AccumReg_0_Accum_Out[22]} {CISC24HW_i/AccumReg_0_Accum_Out[23]}]]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {CISC24HW_i/ExecReg_0_DoutA[0]} {CISC24HW_i/ExecReg_0_DoutA[1]} {CISC24HW_i/ExecReg_0_DoutA[2]} {CISC24HW_i/ExecReg_0_DoutA[3]} {CISC24HW_i/ExecReg_0_DoutA[4]} {CISC24HW_i/ExecReg_0_DoutA[5]} {CISC24HW_i/ExecReg_0_DoutA[6]} {CISC24HW_i/ExecReg_0_DoutA[7]} {CISC24HW_i/ExecReg_0_DoutA[8]} {CISC24HW_i/ExecReg_0_DoutA[9]} {CISC24HW_i/ExecReg_0_DoutA[10]} {CISC24HW_i/ExecReg_0_DoutA[11]} {CISC24HW_i/ExecReg_0_DoutA[12]} {CISC24HW_i/ExecReg_0_DoutA[13]} {CISC24HW_i/ExecReg_0_DoutA[14]} {CISC24HW_i/ExecReg_0_DoutA[15]} {CISC24HW_i/ExecReg_0_DoutA[16]} {CISC24HW_i/ExecReg_0_DoutA[17]} {CISC24HW_i/ExecReg_0_DoutA[18]} {CISC24HW_i/ExecReg_0_DoutA[19]} {CISC24HW_i/ExecReg_0_DoutA[20]} {CISC24HW_i/ExecReg_0_DoutA[21]} {CISC24HW_i/ExecReg_0_DoutA[22]} {CISC24HW_i/ExecReg_0_DoutA[23]}]]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {CISC24HW_i/ExecReg_0_DoutB[0]} {CISC24HW_i/ExecReg_0_DoutB[1]} {CISC24HW_i/ExecReg_0_DoutB[2]} {CISC24HW_i/ExecReg_0_DoutB[3]} {CISC24HW_i/ExecReg_0_DoutB[4]} {CISC24HW_i/ExecReg_0_DoutB[5]} {CISC24HW_i/ExecReg_0_DoutB[6]} {CISC24HW_i/ExecReg_0_DoutB[7]} {CISC24HW_i/ExecReg_0_DoutB[8]} {CISC24HW_i/ExecReg_0_DoutB[9]} {CISC24HW_i/ExecReg_0_DoutB[10]} {CISC24HW_i/ExecReg_0_DoutB[11]} {CISC24HW_i/ExecReg_0_DoutB[12]} {CISC24HW_i/ExecReg_0_DoutB[13]} {CISC24HW_i/ExecReg_0_DoutB[14]} {CISC24HW_i/ExecReg_0_DoutB[15]} {CISC24HW_i/ExecReg_0_DoutB[16]} {CISC24HW_i/ExecReg_0_DoutB[17]} {CISC24HW_i/ExecReg_0_DoutB[18]} {CISC24HW_i/ExecReg_0_DoutB[19]} {CISC24HW_i/ExecReg_0_DoutB[20]} {CISC24HW_i/ExecReg_0_DoutB[21]} {CISC24HW_i/ExecReg_0_DoutB[22]} {CISC24HW_i/ExecReg_0_DoutB[23]}]]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {CISC24HW_i/blk_mem_gen_0_douta[0]} {CISC24HW_i/blk_mem_gen_0_douta[1]} {CISC24HW_i/blk_mem_gen_0_douta[2]} {CISC24HW_i/blk_mem_gen_0_douta[3]} {CISC24HW_i/blk_mem_gen_0_douta[4]} {CISC24HW_i/blk_mem_gen_0_douta[5]} {CISC24HW_i/blk_mem_gen_0_douta[6]} {CISC24HW_i/blk_mem_gen_0_douta[7]} {CISC24HW_i/blk_mem_gen_0_douta[8]} {CISC24HW_i/blk_mem_gen_0_douta[9]} {CISC24HW_i/blk_mem_gen_0_douta[10]} {CISC24HW_i/blk_mem_gen_0_douta[11]} {CISC24HW_i/blk_mem_gen_0_douta[12]} {CISC24HW_i/blk_mem_gen_0_douta[13]} {CISC24HW_i/blk_mem_gen_0_douta[14]} {CISC24HW_i/blk_mem_gen_0_douta[15]} {CISC24HW_i/blk_mem_gen_0_douta[16]} {CISC24HW_i/blk_mem_gen_0_douta[17]} {CISC24HW_i/blk_mem_gen_0_douta[18]} {CISC24HW_i/blk_mem_gen_0_douta[19]} {CISC24HW_i/blk_mem_gen_0_douta[20]} {CISC24HW_i/blk_mem_gen_0_douta[21]} {CISC24HW_i/blk_mem_gen_0_douta[22]} {CISC24HW_i/blk_mem_gen_0_douta[23]}]]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {CISC24HW_i/PCounter_0_Address[0]} {CISC24HW_i/PCounter_0_Address[1]} {CISC24HW_i/PCounter_0_Address[2]} {CISC24HW_i/PCounter_0_Address[3]} {CISC24HW_i/PCounter_0_Address[4]} {CISC24HW_i/PCounter_0_Address[5]} {CISC24HW_i/PCounter_0_Address[6]} {CISC24HW_i/PCounter_0_Address[7]} {CISC24HW_i/PCounter_0_Address[8]}]]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {CISC24HW_i/RegSelMux_0_OutA[0]} {CISC24HW_i/RegSelMux_0_OutA[1]} {CISC24HW_i/RegSelMux_0_OutA[2]} {CISC24HW_i/RegSelMux_0_OutA[3]} {CISC24HW_i/RegSelMux_0_OutA[4]} {CISC24HW_i/RegSelMux_0_OutA[5]} {CISC24HW_i/RegSelMux_0_OutA[6]} {CISC24HW_i/RegSelMux_0_OutA[7]} {CISC24HW_i/RegSelMux_0_OutA[8]} {CISC24HW_i/RegSelMux_0_OutA[9]} {CISC24HW_i/RegSelMux_0_OutA[10]} {CISC24HW_i/RegSelMux_0_OutA[11]} {CISC24HW_i/RegSelMux_0_OutA[12]} {CISC24HW_i/RegSelMux_0_OutA[13]} {CISC24HW_i/RegSelMux_0_OutA[14]} {CISC24HW_i/RegSelMux_0_OutA[15]} {CISC24HW_i/RegSelMux_0_OutA[16]} {CISC24HW_i/RegSelMux_0_OutA[17]} {CISC24HW_i/RegSelMux_0_OutA[18]} {CISC24HW_i/RegSelMux_0_OutA[19]} {CISC24HW_i/RegSelMux_0_OutA[20]} {CISC24HW_i/RegSelMux_0_OutA[21]} {CISC24HW_i/RegSelMux_0_OutA[22]} {CISC24HW_i/RegSelMux_0_OutA[23]}]]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {CISC24HW_i/FSMController_0_RamAddSelB[0]} {CISC24HW_i/FSMController_0_RamAddSelB[1]}]]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {CISC24HW_i/Mux2to1_0_Dout[0]} {CISC24HW_i/Mux2to1_0_Dout[1]} {CISC24HW_i/Mux2to1_0_Dout[2]} {CISC24HW_i/Mux2to1_0_Dout[3]} {CISC24HW_i/Mux2to1_0_Dout[4]} {CISC24HW_i/Mux2to1_0_Dout[5]} {CISC24HW_i/Mux2to1_0_Dout[6]} {CISC24HW_i/Mux2to1_0_Dout[7]} {CISC24HW_i/Mux2to1_0_Dout[8]} {CISC24HW_i/Mux2to1_0_Dout[9]} {CISC24HW_i/Mux2to1_0_Dout[10]} {CISC24HW_i/Mux2to1_0_Dout[11]} {CISC24HW_i/Mux2to1_0_Dout[12]} {CISC24HW_i/Mux2to1_0_Dout[13]} {CISC24HW_i/Mux2to1_0_Dout[14]} {CISC24HW_i/Mux2to1_0_Dout[15]} {CISC24HW_i/Mux2to1_0_Dout[16]} {CISC24HW_i/Mux2to1_0_Dout[17]} {CISC24HW_i/Mux2to1_0_Dout[18]} {CISC24HW_i/Mux2to1_0_Dout[19]} {CISC24HW_i/Mux2to1_0_Dout[20]} {CISC24HW_i/Mux2to1_0_Dout[21]} {CISC24HW_i/Mux2to1_0_Dout[22]} {CISC24HW_i/Mux2to1_0_Dout[23]}]]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {CISC24HW_i/RegSelMux_0_OutB[0]} {CISC24HW_i/RegSelMux_0_OutB[1]} {CISC24HW_i/RegSelMux_0_OutB[2]} {CISC24HW_i/RegSelMux_0_OutB[3]} {CISC24HW_i/RegSelMux_0_OutB[4]} {CISC24HW_i/RegSelMux_0_OutB[5]} {CISC24HW_i/RegSelMux_0_OutB[6]} {CISC24HW_i/RegSelMux_0_OutB[7]} {CISC24HW_i/RegSelMux_0_OutB[8]} {CISC24HW_i/RegSelMux_0_OutB[9]} {CISC24HW_i/RegSelMux_0_OutB[10]} {CISC24HW_i/RegSelMux_0_OutB[11]} {CISC24HW_i/RegSelMux_0_OutB[12]} {CISC24HW_i/RegSelMux_0_OutB[13]} {CISC24HW_i/RegSelMux_0_OutB[14]} {CISC24HW_i/RegSelMux_0_OutB[15]} {CISC24HW_i/RegSelMux_0_OutB[16]} {CISC24HW_i/RegSelMux_0_OutB[17]} {CISC24HW_i/RegSelMux_0_OutB[18]} {CISC24HW_i/RegSelMux_0_OutB[19]} {CISC24HW_i/RegSelMux_0_OutB[20]} {CISC24HW_i/RegSelMux_0_OutB[21]} {CISC24HW_i/RegSelMux_0_OutB[22]} {CISC24HW_i/RegSelMux_0_OutB[23]}]]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {CISC24HW_i/MUXALU_0_ALU_OUT[0]} {CISC24HW_i/MUXALU_0_ALU_OUT[1]} {CISC24HW_i/MUXALU_0_ALU_OUT[2]} {CISC24HW_i/MUXALU_0_ALU_OUT[3]} {CISC24HW_i/MUXALU_0_ALU_OUT[4]} {CISC24HW_i/MUXALU_0_ALU_OUT[5]} {CISC24HW_i/MUXALU_0_ALU_OUT[6]} {CISC24HW_i/MUXALU_0_ALU_OUT[7]} {CISC24HW_i/MUXALU_0_ALU_OUT[8]} {CISC24HW_i/MUXALU_0_ALU_OUT[9]} {CISC24HW_i/MUXALU_0_ALU_OUT[10]} {CISC24HW_i/MUXALU_0_ALU_OUT[11]} {CISC24HW_i/MUXALU_0_ALU_OUT[12]} {CISC24HW_i/MUXALU_0_ALU_OUT[13]} {CISC24HW_i/MUXALU_0_ALU_OUT[14]} {CISC24HW_i/MUXALU_0_ALU_OUT[15]} {CISC24HW_i/MUXALU_0_ALU_OUT[16]} {CISC24HW_i/MUXALU_0_ALU_OUT[17]} {CISC24HW_i/MUXALU_0_ALU_OUT[18]} {CISC24HW_i/MUXALU_0_ALU_OUT[19]} {CISC24HW_i/MUXALU_0_ALU_OUT[20]} {CISC24HW_i/MUXALU_0_ALU_OUT[21]} {CISC24HW_i/MUXALU_0_ALU_OUT[22]} {CISC24HW_i/MUXALU_0_ALU_OUT[23]}]]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {CISC24HW_i/FSMController_0_SBSel[0]} {CISC24HW_i/FSMController_0_SBSel[1]}]]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 24 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {CISC24HW_i/RegisterBank_0_DoutA[0]} {CISC24HW_i/RegisterBank_0_DoutA[1]} {CISC24HW_i/RegisterBank_0_DoutA[2]} {CISC24HW_i/RegisterBank_0_DoutA[3]} {CISC24HW_i/RegisterBank_0_DoutA[4]} {CISC24HW_i/RegisterBank_0_DoutA[5]} {CISC24HW_i/RegisterBank_0_DoutA[6]} {CISC24HW_i/RegisterBank_0_DoutA[7]} {CISC24HW_i/RegisterBank_0_DoutA[8]} {CISC24HW_i/RegisterBank_0_DoutA[9]} {CISC24HW_i/RegisterBank_0_DoutA[10]} {CISC24HW_i/RegisterBank_0_DoutA[11]} {CISC24HW_i/RegisterBank_0_DoutA[12]} {CISC24HW_i/RegisterBank_0_DoutA[13]} {CISC24HW_i/RegisterBank_0_DoutA[14]} {CISC24HW_i/RegisterBank_0_DoutA[15]} {CISC24HW_i/RegisterBank_0_DoutA[16]} {CISC24HW_i/RegisterBank_0_DoutA[17]} {CISC24HW_i/RegisterBank_0_DoutA[18]} {CISC24HW_i/RegisterBank_0_DoutA[19]} {CISC24HW_i/RegisterBank_0_DoutA[20]} {CISC24HW_i/RegisterBank_0_DoutA[21]} {CISC24HW_i/RegisterBank_0_DoutA[22]} {CISC24HW_i/RegisterBank_0_DoutA[23]}]]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {CISC24HW_i/FSMController_0_RegWriteSel[0]} {CISC24HW_i/FSMController_0_RegWriteSel[1]}]]
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 3 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {CISC24HW_i/FSMController_0_RamAddSelA[0]} {CISC24HW_i/FSMController_0_RamAddSelA[1]} {CISC24HW_i/FSMController_0_RamAddSelA[2]}]]
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list CISC24HW_i/FSMController_0_AccumEn]]
set_property src_info {type:XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list CISC24HW_i/FSMController_0_ALUSELB]]
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list CISC24HW_i/FSMController_0_ExecEn]]
set_property src_info {type:XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list CISC24HW_i/FSMController_0_IRWrite]]
set_property src_info {type:XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list CISC24HW_i/FSMController_0_Lprom]]
set_property src_info {type:XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list CISC24HW_i/FSMController_0_PCEN]]
set_property src_info {type:XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list CISC24HW_i/FSMController_0_PCINC]]
set_property src_info {type:XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list CISC24HW_i/FSMController_0_RamWA]]
set_property src_info {type:XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list CISC24HW_i/FSMController_0_RamWB]]
set_property src_info {type:XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list CISC24HW_i/FSMController_0_RegEn]]
set_property src_info {type:XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list CISC24HW_i/FSMController_0_RegRead]]
set_property src_info {type:XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list CISC24HW_i/FSMController_0_RegWA]]
set_property src_info {type:XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list CISC24HW_i/FSMController_0_RegWB]]
set_property src_info {type:XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list CISC24HW_i/ps2Controller_0_WriteEn]]
set_property src_info {type:XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets CLK_IBUF]
