# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include c:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/bd/CISC24HW/ip/CISC24HW_blk_mem_gen_0_0 C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_vhdl -lib xil_defaultlib {
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_ALUMuxB_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_ALU_Shift_Unit_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_AccumReg_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_Arith_Unit_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_DecodeUnit_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_Demux1to2_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_ExecReg_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_FSMController_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_Logic_Unit_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_MUXALU_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_Multiplier_VHDL_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_Mux2to1_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_Mux2to1_1_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_Mux4to1_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_PCounter_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_RamAddAMux_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_RamAddBMux_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_RegSelMux_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_RegisterBank_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_WriteRamMux_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_WriteRamMux_1_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_blk_mem_gen_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_blk_mem_gen_1_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_divider_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_xlconcat_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_xlslice_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_xlslice_1_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_xlslice_2_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_xlslice_3_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_Divider_Clk_0_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_xlslice_4_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/realtime/CISC24HW_xlslice_5_0_stub.vhdl
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/ALUMuxB.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/imports/Desktop/alu_shift_unit.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/AccumReg.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/imports/Desktop/alu_arithmetic_unit.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/DecodeUnit.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/Demux1to2.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/ExecReg.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/FSMController.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/imports/Desktop/alu_logic_unit.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/imports/Desktop/alu_mux.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/imports/new/multiply.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/Mux2to1.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/Mux4to1.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/PCounter.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/RamAddAMux.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/RamAddBMux.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/RegSelMux.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/RegisterBank.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/WriteRamMux.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/imports/new/divider.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/new/Divider_Clk.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/bd/CISC24HW/synth/CISC24HW.vhd
      C:/Users/Aiden/Desktop/CISC24/CISC24.srcs/sources_1/bd/CISC24HW/hdl/CISC24HW_wrapper.vhd
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top CISC24HW_wrapper
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/Aiden/Desktop/CISC24/.Xil/Vivado-2928-DESKTOP-T2T1KVN/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
